### ISSUE TITLE
Notifications: Audit Trail

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#103]
Every interaction has a notification. 

e.g. processor failure + permission to see to fix
e.g. upload success
e.g. added costs

Everything is audited. A complete history of activity.

Two types of notification - one that pops up to get your attention. Another to silently go in there. 

The history of everything related to costs is extra useful so that you can see when something has been added / edited / tweaked / changed.

**Comment by richardbirkin** [comment]
- [ ] style audit table
- [ ] add bell icon in global header

@g105b is there supposed to be something there already that i'm not seeing, up in the global header? I can click on a div but it's blank/invisible/empty.

**Comment by g105b** [comment]
You should see a bell icon when you've uploaded something.

It's styled here: https://github.com/SuperHyperInstantFutureTime/TrackShift/blob/slc2-audit/style/component/global-header.scss#L92-L120

Screenshot:

![image](https://github.com/SuperHyperInstantFutureTime/TrackShift/assets/358014/a6659651-f01e-431c-a651-919f1b33ec6f)

**Comment by richardbirkin** [comment]
aha! have you added the asset in your commit?

**Comment by richardbirkin** [comment]
no i see it there. 
it's not appearing for me though.

**Comment by g105b** [comment]
I've not added anything since Friday, it's on branch `slc2-audit`.

**Comment by richardbirkin** [comment]
well let's just see if it appears when on dev server. it could be a local issue at my end with fetching the svg.

**Comment by g105b** [comment]
Do you have the file in your /asset/icon directory?

**Comment by richardbirkin** [comment]
yeah.

**Comment by richardbirkin** [comment]
note: we just needed to delete the www folder
