### ISSUE TITLE
Uploader: File types

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#126]
New File Types:

.xlsx (e.g. Cargo Physical, Route Note)
.zip (e.g. Cargo Digital - expand the zip and get the `-royalty-extended.csv` file)
.txt (e.g. CD Baby)
.xlsm (e.g Proper Music Distribution PMD))

New .csv file sources: 

- [x] Tunecore
- [ ] Proper Music Distribution Digital (PMD DIGI)
- [ ] Believe

NOTE: Currencies will become an issue when combining Believe (EURO) with Cargo (GBP) and Tunecore (USD)

However, this can be handled in SLC#6. Getting the data in is the first step.

**Comment by richardbirkin** [comment]
@g105b I have made notes on the contents of the Cargo Physical statement columns [here](https://github.com/SuperHyperInstantFutureTime/TrackShift/wiki/Column-Definitions:-Cargo-Physical)

**Comment by richardbirkin** [comment]
@g105b Done the same with Tunecore [here](https://github.com/SuperHyperInstantFutureTime/TrackShift/wiki/Column-Definitions:-Tunecore)

**Comment by richardbirkin** [comment]
@g105b I have added DistroKid files to the shared folder, and done definitions [here](https://github.com/SuperHyperInstantFutureTime/TrackShift/wiki/Column-Definitions:-Distrokid)

**Comment by g105b** [comment]
Noting this repository here for use tomorrow: https://github.com/openspout/openspout

Zip handling is ready but I still need to process the Excel file contents into key-value-pairs, and it looks like this repo is the best way to do it on HUUUUUUGE spreadsheets in a memory-efficient way.

**Comment by richardbirkin** [comment]
Distrokid album sorting: 

Individual rows are songs that have been streamed. The only time you see an Album is if it's been purchased from somewhere like Apple Music. 

UPC is the field that individual songs will have in common when they are on an album. 

We need to use that UPC to group the songs into their album, then fetch the album details/assets from Spotify API. 

NOTE for speed: Any lookup will be per grouping, not per row.

@g105b

**Comment by richardbirkin** [comment]
Testing on the dev branch. 

Tunecore, Distrokid and CD Baby are all working. 

UPC lookup doesn't seem to be working on CD Baby

Cargo physical import isn't working - the file itself does not upload or appear in uploads triggering an error

**Comment by richardbirkin** [comment]
Re: Cd Baby. The column we want is `barcode`

**Comment by richardbirkin** [comment]
@g105b Cargo have changed the naming scheme of their statement. either that or they made a typo on Q3 for GR. 

The filename for Q3 for GR is `123456_2023Q3.xlsx`
This doesn't upload as TS is expecting `123456_2023_Q3.xlsx` - note the underscore separating the year from the period. 

Renaming the file manually works...but we shouldn't expect a user to have to do that. 

Can we allow files with any name, and identify their source based on the header row as before?

**Comment by richardbirkin** [comment]
@g105b Actually...it did work on the second time round. Let me reset and test again...

**Comment by richardbirkin** [comment]
Noticed a mistake in the processing for the Cargo Physical and Digital data. 

In Cargo Digital, you see the album name as written. e.g. `Order of the Toad`

In Cargo Physical, you see the album as the distribution system sees it. e.g. `ORDER OF THE TOAD`

When you import both statements, you get one line of product table for `Order of the Toad` and another for `ORDER OF THE TOAD`

Ideally, they would be combined as one product called `Order of the Toad`

**Comment by richardbirkin** [comment]
Testing with PITP data and found something going a bit dodgy. 

I upload a the smaller Distrokid file
In there is Demain, dès l’aube by From Overseas and zake.
There is an amount of money there £A
The artwork has been found and is visible

I upload the Bandcamp file as well
In there is Demain, dès l’aube by From Overseas and zake. 
There is an amount of money £C which I assume is £A + £B (the earnings for this album within this Bandcamp file)
The artwork is no longer visible

I delete the first Distrokid file from the Uploads table
On the Products Table there is Demain, dès l’aube by From Overseas and zake. 
The amount of money is still £C
The artwork is still not visible


So something is happening with the Bandcamp import where it's not behaving with the data from the Distrokid file that came before it. It's like it overwrites what was there before.

**Comment by richardbirkin** [comment]
Scratch that
I've just repeated the steps and it's just that the `Demain, dès l’aube` earnings from Distrokid are down at the bottom of the Products table. They have not been combined with the Bandcamp earnings for `Demain, dès l’aube`

**Comment by richardbirkin** [comment]
The larger DistroKid file is not processing.
It takes time, so it's doing something. But after 30-60 seconds, you end up at the Uploads table without that file there.
