### ISSUE TITLE
Product table: UNKNOWN UPC

### ISSUE THREAD

**Issue by g105b** [SuperHyperInstantFutureTime/TrackShift#141]
In the product table, we will see the following lines:

- ::UPC::12345678
- ::UNKNOWN_UPC::ABC1234

This comes from streaming platforms where only the track is listed as a sale. As we loop over a statement, we collate matching artist/track names, because sometimes the statement files supply a UPC relating to the album the track is from.

There are two problems:

1. Sometimes, the UPC doesn't relate to anything in Spotify's API or on services like Discogs.
2. Sometimes we don't ever see a UPC, so all we have is an ISRC code for the track (displayed as UNKNWON_UPC)

**Comment by richardbirkin** [comment]
e.g.

artist: Erinome
title: A Burning Down, Pt. 1
ISRC: QZHN81907436

on album: A Burning Down
with UPC: 194838693579

Some earnings have both UPC and ISRC. 
Others have just ISRC. 
So TrackShift should be matching the track to the album, but isn't. 

This album only appears in the larger DistroKid file.

**Comment by richardbirkin** [comment]
re: the problems you wrote up @g105b 

1. nothing we can do about that at the moment without looking into other services. 
2. if we never ever see a UPC for an ISRC, then we should ask Spotify what UPC it has for the ISRC. 

e.g. UNKNOWNUPC::QZFYW2096222

Using [ISRC Finder Reverse Lookup](https://www.isrcfinder.com/reverse-lookup/) we can see that: 
QZFYW2096222 is linked to
120819 by Jörgen Kjellgren

**Comment by g105b** [comment]
The problem as I understand it is when we are _only_ given an ISRC and cannot match it to a UPC within the data sheet - an ISRC lookup via Spotify's API usually fixes the data, because the ISRC can be linked to the album it exists within - but the problem is that the ISRCs that are provided in the sheet do not match anything within Spotify (or any other lookup services for that matter).

We technically _could_ search the song title via Spotify and find the matching album, but when there are compilation albums and EPs we can't make assumptions.

Quite often, the more popular "album" a track exists on is the EP release or a compilation album, so we would end up incorrectly allocating the track.

Is this a problem that we have to solve within TrackShift itself? Maybe on the Product page we can manually select the correct album?

**Comment by richardbirkin** [comment]
The example that we're working on is actually data that is quite old - more than five years old in fact. 

It is entirely possible that the label has re-mastered / re-issued the release that is in the old data, while rectifying/changing the meta data - which is what we can see has happened in our example. 

To continue trying to fix old data will not be the best use of time at the moment. 

A better use of time would be to make it so that a user can normalise their own data in an efficient way within TS. 

e.g. 

Search for the artist in the Product Table
Bulk Edit the tracks that are not part of an album
Save as the album. 

This way we'll be using the TS Album object, and each track within it will have all of these different meta data values - this is in itself valuable as it shows a paper trail of metadata for a recording over time.

**Comment by richardbirkin** [comment]
In the Product Table we are currently showing `::UNKNOWN_UPC::ABC1234` as a debug when we can't match a recording with a product.

For now, let's change this back to Track Title, but also have a <small> message below it saying `Could not match the ISRC to a distributed recording`

**Comment by g105b** [comment]
Your idea above is a 10 minute change, compared to the work involved in creating a new page or merging functionality.

An idea I've just had is when TS finds "UNKNOWN_UPC" or whatever, it shouldn't add it to the list of products at all. Instead, we should have a special page called "unsorted stuff" which can show something like "You have 18 unsorted tracks with a total of £4,200" where you can perform the allocation to existing products.

**Comment by richardbirkin** [comment]
Let's look at a more recent Distrokid report from 2023 and make sure that all the sortable tracks are getting sorted. 

Then:

Phase 1: <small>Could not match the ISRC to a distributed recording</small>

Phase 2: New page - Unsorted tracks.

**Comment by richardbirkin** [comment]
This: 
::UNSORTED_UPC::195915179467

Should be displayed as:
Unknown Album
(UPC: 195915179467)

::UNSORTED_ISRC::195915179467
Track Title
(Cannot find matching album using ISRC: 195915179467)
