### ISSUE TITLE
Uploads: cache earnings for uploads and products

### ISSUE THREAD

**Issue by g105b** [SuperHyperInstantFutureTime/TrackShift#142]
Currently the earnings are calculated every page render, but when there are hundreds of thousands of usages, render times start getting quite slow.

The total earnings can easily be cached on the upload. Products probably need to have some sort of invalidation technique so they can update when there's more usages imported.

**Comment by g105b** [comment]
As said above, upload earnings will cache perfectly easily: a new field on the Upload table to record the earning once.

Products will need invalidating. This can be done by introducing a single new field on the Product table for cached earnings. When a new usage is processed that touches this product, we can set this cache to null, forcing it to be recalculated again.

**Comment by richardbirkin** [comment]
Bug reported #152

**Comment by richardbirkin** [comment]
Bug reported #154
