### ISSUE TITLE
Splits: OK button should automatically add a split if there's data in the row

### ISSUE THREAD

**Issue by g105b** [SuperHyperInstantFutureTime/TrackShift#144]
- Given I am on the splits page
- When I follow "Add new split"
- And I select "Colourful Cartons" from "Artist"
- And I select "Umbongo" from "Track"
- And I enter "Greg" into "Split owner"
- And I enter "12%" into "Split amount"
- And I press "OK"
- ❌ Then I should see 1 split to "Greg" for "12%"

The OK button dismisses the window, but if there's new data in the row and the user hasn't yet pressed the add button, the add button should be automatically clicked before continuing.

**Comment by richardbirkin** [comment]
@g105b not sure if this was supposed to be on the latest deployment to normalisation dev branch but it's not fixed there
