### ISSUE TITLE
A user should be able to see combined royalties data 

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/Trackshift#15]
**Feature:** Statement Upload and Processing
In order to combine and reformat music royalties data into something i can quickly understand
As an artist user
I need to be able to upload a file and have it processed

Rules:

- Files are .csv files

**Scenario: Set a cookie**
Given that I am a new user
And there is no cookie for Trackshift previously set
Then Trackshift should create a session cookie in my browser

**Scenario: Successfully upload a file(s)**
Given that I have one or more royalty statement .csv file
When I upload them
And they have passed validation
Then I should see that they have been uploaded
And that they are being processed

**Scenario: Unsuccessfully upload a file(s)**
Given that I have one or more royalty statement .csv file
When I upload them
And they have failed validation
Then I should see that they have not been uploaded
And I should see information about the required file types

**Scenario: Store the file(s)**
Given that I have successfully uploaded a file
Then a temporary folder should be created
And linked to the session cookie that has already been set 

Scenario: Validate the file(s)

Scenario: Process the data from file(s)

TBD: UML

Scenario: A user can see the combined data

Scenario: A user can register

Scenario: Unregistered data is removed

**Comment by g105b** [comment]
The latest code shows a breakdown of the latest upload. Next feature is to combine multiple uploads into one aggregation.
