### ISSUE TITLE
ProductTable: Negative Balance showing as less than a penny

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#164]
If a product has an earning of 1000
and a cost of 2000
then the balance should be -1000

Currently, because of the code that shows <0.01 for earnings less than a penny, all numbers that are negative are being rendered as <0.01 instead of their negative value

**Comment by g105b** [comment]
Referencing https://github.com/PhpGt/DomTemplate/issues/491 as this will be the long-term solution.
