### ISSUE TITLE
Nofifications: Anon v Registered banner

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#175]
@g105b I'd like to put a banner on the dashboard for users who are using TS but are not registered. 

Can you show me how to do this pleeeeeeease?

**Comment by g105b** [comment]
```php
function go(Authenticator $authenticator, HTMLDocument $document):void {
	if(!$authenticator->isLoggedIn()) {
		$document->querySelector("the-thing-that-appears")->hidden = false;
	}
}
```

**Comment by richardbirkin** [comment]
@g105b _common.php says I can't redeclare go()

**Comment by richardbirkin** [comment]
@g105b yeah that's where I am

**Comment by g105b** [comment]
What's the path of the file you're editing?

**Comment by richardbirkin** [comment]
page/account/_common.php

**Comment by g105b** [comment]
What branch are you on?

**Comment by richardbirkin** [comment]
slc5-biff-styles

**Comment by g105b** [comment]
It looks to me like this is code from before the HTML components were extracted into the _component directory. There currently shouldn't be anything in that file, so it would be worth starting a new branch _from_ slc7 or master, or if you think you dare, merging master into your current branch.

**Comment by richardbirkin** [comment]
i dare!

**Comment by g105b** [comment]
11:37 -> 12:51. Didn't take too long :)

**Comment by richardbirkin** [comment]
This has been added in `slc7-biff-styles`

**Comment by richardbirkin** [comment]
Tested and approved
