### ISSUE TITLE
Business Development Grant Funding

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/Trackshift#26]
Pursue a Smart Grant from Innovate UK.

- [x] Setup company with Companies House
- [x] Speak to University of Derby
- [x] Speak to Nottingham University
- [x] Speak to Nottingham Creative Quarter Business Advisor
- [x] Speak to The Big House (if they're still going)

The funding for The Big House and Real Creative Futures has come to an end. I have emailed some of the bid writers and consultants involved, and followed them on LinkedIn. 

We aren't recent enough graduates of Derby Uni to qualify for any business support, but I have emailed John Crossley at the music department as he's a good egg, and as well as an educator he's a composer and label owner. 

I'll keep trying to find any support from Nottingham Uni but nothing so far. I think it's probably better starting at Confetti ICT as they are focussed on music and media training, so will most likely be of help for extending our network more than funding or business advice.

- [x] Attend Derby networking event 26th November
- [x] Find out about new Innovate UK regional fund that launches in 2023
- [x] Speak to Advantage Creative
- [ ] Find a contact at Confetti ICT 

At the Business Gateway event last week I spoke to Jay from Dubrek and he can help link me up with Derby Uni and Confetti contacts who helped him set up Dubrek.

- [ ] Speak to Simon at Digit about Board of Advisors
- [x] Put in formal EOI for new Innovate UK Create Growth Fund
- [ ] Research Creative Catalyst fund via Innovate UK

"UK registered micro/SMEs in the creative sector, in six specified regions of England, can apply for £10k-£30k for innovation projects to grow their business."

**Comment by richardbirkin** [comment]
Spent 2h on this today. Some good leads, and lots of emails fired off to new contacts.

**Comment by g105b** [comment]
Nice, do you want to list the business info and link to Companies House on the wiki somewhere that makes sense?

**Comment by richardbirkin** [comment]
Good idea - will do

**Comment by richardbirkin** [comment]
@g105b https://github.com/SuperHyperInstantFutureTime/Trackshift/wiki/Company-Details

**Comment by richardbirkin** [comment]
re: contact at Confetti. Jay from Dubrek has a lead on this. 

have sent followup emails on last Friday's event about where to send an Expression of Interest for the new fund

**Comment by richardbirkin** [comment]
This is[ the new Innovate UK fund](https://apply-for-innovation-funding.service.gov.uk/competition/1394/overview/2b029a32-ac25-457d-9f36-786b3ef746bc#summary)

**Comment by richardbirkin** [comment]
Since we got the Innovate UK funding, I'm going to close this task.
