### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by g105b** [SuperHyperInstantFutureTime/Trackshift#29]
This is not just a legal document that's written once and sent out to die. To make user privacy a feature, the policy should be defined in code, so the code applies our decisions by default - the policy document can then be output according to the code to give a layer of confidence that we are actually sticking to our own policies.

We can start this from scratch, as we have with everything else, so we only have to add a rule to the policy when we come to making a decision that affects user privacy.

Current rules include:

+ [x] Data retention period
+ [x] Use of cookies and other tracking techniques
+ [x] Sharing of data - our system is closed, we do not send data anywhere, but it's important to lay it out in black and white
+ [x] What we do with your data while we have it - this is a bit fuzzy, but I wonder if there's a way we can encrypt the data at rest, so its impossible for even us to see it, and whether this is something we would even want to or need to do?

Tagged @richardbirkin on this too because it's something we need to talk about to flesh out a bit more.

Side note for Biff. I notice you've started a Projects board. Do you think I should tag new issues into the board when I create them, or is this something you'll do when you come to check over the project?

**Comment by richardbirkin** [comment]
@g105b re: Projects board. I was just messing about to see if it's something we should use. I think the aims for Release 1 are concise and well understood enough to be contained as Milestones within Issues.

**Comment by richardbirkin** [comment]
When we start using a database there will be some important discussions to be had about data retention. 

For instance, in a row of PRS Distribution Statement data, some of it is searchable in the public domain. Like Work Title, Tunecode. And when we process distributor data, there is ISRC code, duration and the writers of a tune. 

There is other data that is obviously private. A user's CAE/ICI Number, amounts of money, usages etc. 

Of course, the user should be allowed to nuke ALL data if they are not getting value from TrackShift.

**Comment by richardbirkin** [comment]
re: encrypting the data in storage. i think this is a very good idea. what's the time hit on something like that @g105b ?

**Comment by g105b** [comment]
It's a good idea to do it, but I'm going to suggest to implement it later, as I think during the initial development phase it will be really useful for us to be able to see the data that's being uploaded.

**Comment by richardbirkin** [comment]
@g105b how far did you get with this last week?

**Comment by g105b** [comment]
It's in the PR: https://github.com/SuperHyperInstantFutureTime/Trackshift/blob/70e8825758016ddbf4096b100d113d3db47595a4/page/privacy.html
