### ISSUE TITLE
Automatic deletion of data with countdown

### ISSUE THREAD

**Issue by g105b** [SuperHyperInstantFutureTime/Trackshift#30]
All data that enters the system will have a retention policy applied to it, but to keep the user informed about this, it needs to be articulated in the web interface.

+ [x] Your data will be deleted in X days/hours/minutes
+ [x] Click here to keep your data on our system for another week
+ [x] Explainer of what all this means, with link to the priv. pol.

**Comment by richardbirkin** [comment]
@g105b i've seen the first two tasks from the list, but not the last one.
