### ISSUE TITLE
Add Minimal CSS

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/Trackshift#38]
Plain old classic HTML might be beautiful to us, but may be off putting to others. 

Following the [Better Motherfucking Website ](http://bettermotherfuckingwebsite.com/) model of only a few lines of code, we should be able to make TrackShift look more contemporary by:

- [x] define a container
- [x] choose a web font
- [x] increase line height
- [x] minimal table styling
- [x] subtle black/white contrast

**Comment by richardbirkin** [comment]
@g105b I'm feeling like using Gilroy again for old time's sake

**Comment by g105b** [comment]
Gilroy coming up!

![image](https://user-images.githubusercontent.com/358014/204353693-920340e7-d648-40c6-99f1-aa9ebd028784.png)

**Comment by richardbirkin** [comment]
Yeah let's do it. I was tempted to say let's keep it system based, but I do like the look of Gilroy. It's not too showy and it's very legible.
