### ISSUE TITLE
Local Dev Install not working

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/Trackshift#59]
I have a brand new macbook. 
Went through all steps and everything worked. 

`cd` to /trackshift and hit `gt run` and `gt command not found`

**Comment by g105b** [comment]
This means that the `~/.composer/vendor/bin` is not in your PATH for some reason. If you type `echo $PATH`, what is output? If you _do_ see ~/.composer/vendor/bin`, then maybe the `composer global require phpgt/gtcommand` command was not run?

**Comment by g105b** [comment]
Yeah! No Composer in there... I wonder why that was not added?

A bit more debugging, please can you let me know the output of:

+ `composer --version` - to check if Composer is installed correctly at all
+ `ls ~/.composer/vendor/bin` to see if the gt command is installed
+ `cat ~/.bash_profile` to see your bash settings

Ahhhhh... maybe new Macs don't run Bash??? This might be the epiphany I needed...

+ `echo $SHELL` - is it Bash? If not, our PATH won't be adjusted by the steps I recorded in the Wiki

**Comment by richardbirkin** [comment]
re: your past point. 

result of `echo $SHELL` is `/bin/zsh`

**Comment by g105b** [comment]
There we go! So it's added the Composer directory to your bash's PATH, not zsh's PATH.

I'll have to think how to change the wiki so it works for any shell, but for now you can do this:

`echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> ~/.zshrc`

Then restart your terminal, and you should be able to see a response to the following commands:

+ `gt --version`
+ `composer --version`
+ `webpack --version`
+ `sass --version`

Can you confirm?

**Comment by richardbirkin** [comment]
Done. 

I can confirm those 4 --version checks all worked.

**Comment by g105b** [comment]
Nice, can you `gt run` trackshift now then?

**Comment by richardbirkin** [comment]
Yep!

**Comment by richardbirkin** [comment]
Thanks @g105b

**Comment by g105b** [comment]
Super duper!
