### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#73]
We could do with a Landing Page for people to find out about what we do to lend a bit of a face to the product, prior to the product being ready. 

## What value are we adding?

A user can see what we're about. 

## Specification

A logo
X-statement
Elevator Pitch
Coming Soon banner. 

Nothing too complicated for version 1. 

In the future we can have some featurettes describing key features, or a video explaining the product.

**Comment by richardbirkin** [comment]
@g105b can you create the page and I will populate?

**Comment by richardbirkin** [comment]
- [ ] Create page in phpGT
- [ ] Create Content
- [ ] Set DNS
- [ ] Choose email provider
- [ ] Setup email
- [ ] Set MX

**Comment by g105b** [comment]
We can define the 3 SLC deliverables this task will cover tomorrow.

**Comment by richardbirkin** [comment]
## Simple

**What is the value add that increases simplicity?**

People want to know/share what we are doing, and need somewhere to link to that says what we do. 

The journalistic approach to this is:

- who
- what
- why
- how
- when
- where

So that's the content heirarchy for the page right there.

## Loveable

**A great User Experience. Beautiful to look at and use. An engaging and appealing tone of voice.**

This is a task that we can give to Jim Cork at Explore Studio (our designer on the IUK project) once we have written the content. 

## Complete

**What completes the user journey?**

A call to action. Sign up for updates/early adopters. Share.

**Comment by richardbirkin** [comment]
@g105b can you create the index.html page in phpGT please?

**Comment by g105b** [comment]
I'm such a fan of the simplicity of Markdown, and how it helps focus on the important things, that [I have created the first Markdown file for web content](https://github.com/SuperHyperInstantFutureTime/Trackshift/blob/web-content/data/web-content/homepage.md). I'll hook it up to a simple index.html later so it can be used as the CMS-less CMS. Do you want to start filling it with content? If you keep the structure similar to how I've started it, it'll be easy to generate the page using it.

**Comment by richardbirkin** [comment]
Yep, great starting point.
