### ISSUE TITLE
User can connect TS account to Bandcamp account (API)

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#79]

**Comment by g105b** [comment]
https://bandcamp.com/developer

Looks like we need to request access to the API, and Bandcamp are on holiday at the moment. Would you like to explain TS to them via [the request form](https://bandcamp.com/contact?subj=API%20Access), so it's ready when I have the availability?

**Comment by richardbirkin** [comment]
You got it

**Comment by richardbirkin** [comment]
> Thanks for your interest. Our APIs are currently limited to Label Accounts ([bandcamp.com/labels](http://bandcamp.com/labels)) looking to pull physical order and general sales information, though that might change down the road. Please keep an eye on [bandcamp.com/developer](http://bandcamp.com/developer) for updates.

**Comment by richardbirkin** [comment]
My reply: "Thanks for getting back to me so quickly! Label accounts are the ones that we'd like to connect with TrackShift. Our prototype (that got us the funding) was built to import a Bandcamp sales CSV. We're just looking to get API access to allow our label users to manage their sales data without having to get a CSV file and upload it to our service.

Would that be possible?"

**Comment by richardbirkin** [comment]
> I'm afraid API access can only be granted to existing label accounts on Bandcamp and not to a third party, sorry about that.

**Comment by richardbirkin** [comment]
So I could pay for a label account and request API Access, but would only be able to query my own label. 

If any other label wants to connect TS to BC, they would have to request a key from BC and enter it into TS.

For now at least.

**Comment by richardbirkin** [comment]
## Plan A

User connects TS to Bandcamp for transfer of Sales and Product data. 

*Problem:* API Access currently only granted to individual label accounts. 

*Solution:* Get in touch with a senior dev or dev representative at Bandcamp to discuss access or expansion of API

## Plan B

User downloads a sales report from Bandcamp and uploads it to TS

TS creates table of products and earnings - DONE

TS uses EAN/ISRC to query Spotify/Apple Music APIs to import artwork, meta, stats, permalink - anything available

**Comment by richardbirkin** [comment]
https://developer.spotify.com/

https://developer.apple.com/musickit/

https://developer.apple.com/documentation/applemusicapi

**Comment by richardbirkin** [comment]
A new thought:

## Plan C

I get a Bandcamp label account and request API Access. Then if a label does want to automate everything they can request access directly from Bandcamp and put their API key details into TrackShift

**Comment by g105b** [comment]
This doesn't feel like the slick'n'floaty experience we want... I wonder whether it's possible to get access to their sales data without an API, or using some other method?

**Comment by g105b** [comment]
> A new thought:
> ## Plan C
> 
> I get a Bandcamp label account and request API Access. Then if a label does want to automate everything they can request access directly from Bandcamp and put their API key details into TrackShift

Alternative idea: when logged in to BC as a label, is there any way you can provide another person access to your label? If so, they could provide our TS user access, and we could grab the data on their behalf. I'm sure this would be frowned upon by BC though, because it's essentially screen scraping, and not much different to TS asking for the BC user's login credentials and scraping it directly... hmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by richardbirkin** [comment]
My thoughts exactly. It's the next most logical thing but it doesn't feel like a SHIFT thing to do. 

I think we carry on with file uploads, use other APIs to fill in the gaps of meta and grab assets. Then, after we launch, we'll approach Bandcamp with the idea. 

We also never know who we're going to meet on the investor trail n'all

**Comment by g105b** [comment]
Good points. Maybe this is a good excuse to keep the simple _simple_. Getting data from APIs is nice, but if we can continue with file uploads it enhances simplicity of the code even more, for longer... it's just an enforced simplicity that we weren't planning on, but we've got to play well with Bandcamp (even though I've just read over [their TOS](https://bandcamp.com/terms_of_use) and it doesn't sound like we would violate any rules with my ideas above).

**Comment by richardbirkin** [comment]
yep. it's not the right approach. 

currently the simple simple way is to get the file, which is the only thing you have to work with, and upload it to TS instead of loading it up in sheets/excel/numbers and crunching it.

**Comment by richardbirkin** [comment]
But I think we still utilise available APIs in the background to pull in everything we can about a tune, album, product.
