### ISSUE TITLE
SLC 2: Multiple Artists + Multiple Data Sources + DSP APIs

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#81]
<img width="1153" alt="Screenshot 2023-07-11 at 14 31 23" src="https://github.com/SuperHyperInstantFutureTime/Trackshift/assets/115098450/f0527d02-ef1c-4933-a562-5ff47308304c">

Table should default to sorted by Artist alphabetal ascending, but the user should be able to sort the table by any column header ascending or descending

User should also be able to search from the top of the table, with the table excluding none matches to artist or release title as characters are added

**Comment by richardbirkin** [comment]
<img width="567" alt="Screenshot 2023-07-11 at 14 44 16" src="https://github.com/SuperHyperInstantFutureTime/Trackshift/assets/115098450/545500a2-ea34-463f-86fd-829fb30b8a67">

**Comment by richardbirkin** [comment]
TBD: how we approach 'recoupable' as an option. 

Let's assume now that all costs entered in TrackShift are the ones that are recoupable before a balance can be shared out.

**Comment by richardbirkin** [comment]
<img width="554" alt="Screenshot 2023-07-11 at 14 51 10" src="https://github.com/SuperHyperInstantFutureTime/Trackshift/assets/115098450/ceed5f9e-9cc3-4e80-afdd-5294b6bdb612">


TBD: adding contacts for each Share holder so that they can be sent distribution statements from the label

**Comment by g105b** [comment]
A couple of questions that I have from reading through these messages:

1. When the label is adding their own share, is the "distributable" amount calculated every month, or can the period be dynamic too?
2. Are the costs one-off or repeating for each payout period?

Regarding your recoupable question, it's probably best to ask an actual label where the gaps in functionality are, as otherwise we'd be risking building functionality that solves nobody's problems.

**Comment by richardbirkin** [comment]
2. As far as we currently know, the costs are one-off e.g. manufacturing vinyl £1500, PR agency £500, Facebook promotion £100. 

1. The distributable amount is the gross profit divided by the share splits. If there has been a payment, then a credit should be applied to the distributable that is specific to a period. 

My brain is a bit fried to unpick this now, but I'll do it at your house tomorrow.

**Comment by richardbirkin** [comment]
For an album that has a 50/50 split between band and label....

### Month 1 

Costs £3000

Earnings £4000

Distributable = 0.5 * £1000 = £500

Retained Profit = £500

_Label pays the £500 to the artist_

### Month 2

Costs £3000 (nothing new added)

Earnings (another £2000 brings total Earnings to) £6000 

Distributable = 0.5 * £3000 = £1500 - £500 credit from Month 1 = £1000

Retained Profit = £1500


You could also write it like this...

Retained Profit (all time) = £1500
Retained Profit (month 1) = £500
Retained Profit (month 2) = £1000

Not sure if that clarified anything or not.
