### ISSUE TITLE
ProductAggregations list: Album cover art

### ISSUE THREAD

**Issue by g105b** [SuperHyperInstantFutureTime/TrackShift#83]
We'll have all the ability to load album art from DSPs. I'm currently in the process of making a lovely self-documenting Spotify API client, so I'll use that.

**Comment by richardbirkin** [comment]
I've done some documentation around the columns that we need to grab from each line to infer what has had a usage, what version it is, and what universal identifiers there should be for referencing third party APIs or grouping tunes into albums and products. 

## Cargo Physical

This comes as a .xlsx file and contains sales of physical products (vinyl, CD, tape etc.)

Perfect for assembling 'albums' as a group of 'tunes'

<img width="1069" alt="Screenshot 2023-08-01 at 19 51 19" src="https://github.com/SuperHyperInstantFutureTime/TrackShift/assets/115098450/a02956bc-a649-4576-84fe-b0df493607e3">

## Bandcamp

We're pretty familiar with this now, so just adding for reference and to capture our current thinking as I understand it. 

Column C tells us what has had a usage. `track` is a single track purchase, `album` is an album 
Column D is the `title` of the thing. 
If the thing is a `track` then its `ISRC` will be in column AG (if an ISRC has been supplied).
If the thing is an `album` then its `UPC` will be in column AF (if a UPC has been supplied).
The `product` version of the thing is in AA
The `artist` is in E.

<img width="836" alt="Screenshot 2023-08-01 at 19 52 57" src="https://github.com/SuperHyperInstantFutureTime/TrackShift/assets/115098450/72817c25-bdef-40ee-812a-79fd50036586">

## Cargo Digital

<img width="1061" alt="Screenshot 2023-08-01 at 19 52 02" src="https://github.com/SuperHyperInstantFutureTime/TrackShift/assets/115098450/4dfeecd1-5a71-4d4f-9200-0a34de97e2cc">

**Comment by richardbirkin** [comment]
It's working a lot better now. 

We should add 'Compilation' to the search terms. 

The Gringo Records compilation 'Oh Yeah!' by Various Artists is coming back with Roxy Music artwork. 

Also 'Polaris' by Polaris is returning 'Polaris' by Aitch

Also 'Life is Short' by Broken Arm is returning 'Life is Short' by Dabongz x Bradderz.

**Comment by richardbirkin** [comment]
and 'what's wrong with you' by Sweet Williams is not returning anything. I've checked and it is there in Spotify.

**Comment by richardbirkin** [comment]
The artwork grabbing is incredibly fast now, and after some rounds of testing with our test sales data, is really reliable at getting the right artwork.
