### ISSUE TITLE
UploadsTable: total earnings

### ISSUE THREAD

**Issue by richardbirkin** [SuperHyperInstantFutureTime/TrackShift#95]
I think we should add an earnings column to the Uploads table so that the user can see check the total value of a statement against what hits their bank

**Comment by g105b** [comment]
![image](https://github.com/SuperHyperInstantFutureTime/TrackShift/assets/358014/05823f22-6bb5-48d4-958a-55cda64e5515)

**Comment by richardbirkin** [comment]
Notes for my styling:

- [ ] Centre text in Date/Total columns
